kind: Service
apiVersion: v1
metadata:
  name: restapi
  labels:
    app: restapi
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  selector:
    app: restapi
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 3000
